feat: New media route
APISuite/apisuite-be pull request #46
Opened 2021-10-01 16:45 UTC by Joao-Castilho

New media route

2021-10-01 17:11 UTC, s1moe2 requested changes

2021-10-01 17:11 UTC, s1moe2 commented on controllers/media.js
> +  if (!mediaSearch) return res.status(HTTPStatus.NOT_FOUND).send({ errors: ['Image not found'] })
if media object not found, return 204 nevertheless?

2021-10-01 17:11 UTC, s1moe2 commented on controllers/media.js
> +  await models.Media.destroy({
consider switching?

2021-10-01 17:11 UTC, s1moe2 commented on models/media.js
> +    id: {
consider using file as PK

2021-10-01 17:11 UTC, s1moe2 commented on routes/media.js
> + *       - name: orgId
orgId vs route4 defined appId

2021-10-01 17:11 UTC, s1moe2 commented on routes/media.js
> + *       - name: OrgId
Orgid vs orgId

2021-10-04 11:47 UTC, Joao-Castilho commented on controllers/media.js
> +  for (const key in req.formdata.files['']) {
It must be

2021-10-04 13:42 UTC, s1moe2 requested changes

2021-10-04 13:42 UTC, s1moe2 commented on controllers/media.js
> +  const imageURls = []
not being read

2021-10-04 13:42 UTC, s1moe2 commented on controllers/media.js
> +  for (const key in req.formdata.files['']) {
Should iterate `.files` and uploaded files should be identified by a key in the form-data request

2021-10-04 13:42 UTC, s1moe2 commented on controllers/media.js
> +  const file = req.query.mediaUrl.substr(req.query.mediaUrl.indexOf('/media/') + 7, req.query.mediaUrl.length)
Repeated code. Consider moving into function?

2021-10-04 13:42 UTC, s1moe2 commented on controllers/media.js
> +  const mediaSearch = await models.Media.findByPk(file, { transaction })
Should be part of the transaction

2021-10-04 13:42 UTC, s1moe2 commented on controllers/media.js
> +  if (!mediaSearch) return res.status(HTTPStatus.NOT_FOUND).send({ errors: ['Image not found'] })
Should commit/rollback the transaction

2021-10-04 13:42 UTC, s1moe2 commented on migrations/20211001142037-create-media.js
> +        allowNull: false,
Missing FK `references` object property

2021-10-04 13:42 UTC, s1moe2 commented on models/media.js
> +
Missing relation to organization

2021-10-04 15:06 UTC, s1moe2 requested changes

2021-10-04 15:06 UTC, s1moe2 commented on controllers/media.js
> +  await storageClient.deleteFile(path)
Shouldn't this happen before the model destroy (and commit), therefore preventing the model to be deleted if the image delete fails?

2021-10-04 15:06 UTC, s1moe2 commented on migrations/20211001142037-create-media.js
> +        allowNull: false,
This is not resolved. The created table has no FK.
<img width="831" alt="imagem" src="https://user-images.githubusercontent.com/36140182/135875869-caa4559f-d9f9-4e26-99bf-151bbb1fd098.png">

2021-10-04 15:28 UTC, s1moe2 approved these changes

2021-10-04 15:29 UTC, merged